### ISSUE TITLE
Duplicate values defined for "client_secret" parameter - LinkedIn SSO

### ISSUE THREAD

**Issue by antonionieto** [tomasvotava/fastapi-sso#141] opened 2024-03-23 10:49 UTC
Hey, 

I am trying to use the LinkedIn SSO provided by @Cereal84 and I am getting some issues. First, I tried it with my own app and I was getting the error: `Duplicate values defined for "client_secret" parameter`. Then, I just tried to execute the provide [example](https://github.com/tomasvotava/fastapi-sso/blob/master/examples/linkedin.py) and I got the same error.

Sharing a snapshot of the error message I got on the terminal:

![image](https://github.com/tomasvotava/fastapi-sso/assets/17590067/be5fcb18-dfe8-4a90-b2fb-cb1f4a4cf8b8)

Any thoughts why this may be happening? Thanks in advance!

**Comment by Cereal84** [comment] 2024-03-23 18:57
Hi @antonionieto,
thank you, probably  I forgot something when I pushed the code due It works on my project.
I'll take a look ASAP

**Comment by Cereal84** [comment] 2024-03-23 18:58
@tomasvotava can you assign this issue to me ?

**Comment by tomasvotava** [comment] 2024-03-23 21:22
Hi, thank you guys both!

**Comment by Cereal84** [comment] 2024-03-23 22:29
Versions 0.11.0 and 0.12.0 works correctly so in meantime you can use one of them.
I've to check the differences with the 0.13.0

**Comment by Cereal84** [comment] 2024-03-23 23:13
@tomasvotava The problem is this section of code in the base.py file

```python
        auth = httpx.BasicAuth(self.client_id, self.client_secret)

        if pkce_code_verifier:
            params.update({"code_verifier": pkce_code_verifier})     # here

        async with httpx.AsyncClient() as session:
            response = await session.post(token_url, headers=headers, content=body, auth=auth, params=params) #here
```
In the specific the **params=params** contains the extra params added by *_get_extra_params* and for Linkedin provider contains the key *client_secret*.

I don't know the logic and the meaning of adding params into session.post() and if we need to create a new dictionary for **pkce_code_verifier** without the extra params added by LinkedIn Provider or other Providers.

**Comment by tomasvotava** [comment] 2024-03-24 12:47
Oh, that's what I added recently :| I think we need to merge the params so that we remove duplicates in some clever way, thanks for catching this. Will you be able to create some PR and merge the dicts or should I?

**Comment by chrisK824** [comment] 2024-03-26 18:08
I've stumbled upon this one as well @tomasvotava . Indeed the 'client_secret' is present both in query parameters and body, hence the server side is complaining for duplicate (I guess they shouldn't and should just accept one location, but whatever..)

**Comment by tomasvotava** [comment] 2024-04-02 08:46
Yes, this is a leftover oopsie from my latest changes, @Cereal84 should I take over this issue?

**Comment by Cereal84** [comment] 2024-04-02 15:00
> Yes, this is a leftover oopsie from my latest changes, @Cereal84 should I take over this issue?

I apologize for my silence in these days but I didn't have and don't have the time on work on it due to over commitments. So please take over It @tomasvotava .

I'm sorry.

**Comment by tomasvotava** [comment] 2024-04-02 16:39
Could any of you guys take a look at the branch in the PR #147? I believe this could resolve the problem, but I currently do not have a LinkedIn oauth app to test it with.

**Comment by chrisK824** [comment] 2024-04-02 17:21
I will try it tomorrow when I find some minutes sir!

**Comment by chrisK824** [comment] 2024-04-03 17:01
@tomasvotava I can happily confirm LinkedIn SSO  works now :) 

I've also checked the following providers and nothing has broken:
1. facebook
2. X (Twitter)
3. GitHub
4. GitLab
5. Microsoft
6. Google
7. Spotify

P.S I have been doing some Medium articles around your useful library and demonstrating them in this repo https://github.com/chrisK824/fastapi-sso-example

**Comment by tomasvotava** [comment] 2024-04-03 17:08
OMG @chrisK824, that's cool! Thank you so much for testing those classes, that's super helpful!

It feels awesome that someone is actually using this package and now there are Medium articles, too 😳

**Closed** 2024-04-03 17:08 UTC

**Comment by Cereal84** [comment] 2024-04-03 18:59
> @tomasvotava I can happily confirm LinkedIn SSO  works now :) 
> 
> I've also checked the following providers and nothing has broken:
> 1. facebook
> 2. X (Twitter)
> 3. GitHub
> 4. GitLab
> 5. Microsoft
> 6. Google
> 7. Spotify
> 
> P.S I have been doing some Medium articles around your useful library and demonstrating them in this repo https://github.com/chrisK824/fastapi-sso-example
> 
> There are tutorials for:
> 1. facebook
> 2.  GitHub
> 3. Microsoft
> 4. Google
> 5. Spotify
> 
> and preparing 3 more on:
> 1. X (Twitter)
> 2. GitLab
> 3. LinkedIn
> 
> Let me know if you are interested in referencing any of the above in your documentation. Cheers!

Nice :)

**Comment by Cereal84** [comment] 2024-04-03 19:08
> Well it's great work @tomasvotava , it's only natural hehe
> 
> I was actually thinking of deploying that example in some free plan vercel instance for demo purposes.
> 
> Would make it easy for anyone to see the experience, and for people like you to test with as many providers possible after releases hehe 

@tomasvotava you deserve It, great library and work.

**Comment by tomasvotava** [comment] 2024-04-03 20:43
I was just thinking we should have some integration tests, but since the whole oauth procedure requires a user interaction, deploying it live somewhere is a perfect solution! Vercel is a good idea, I won't be able to publish LinkedIn yet, TBH I haven't found an option to create an oauth app without creating a company on LinkedIn first 🤔

**Comment by chrisK824** [comment] 2024-04-03 21:11
Sure, live demo on the way, hopefully until next week. 

Regarding LinkedIn, no worries, got you covered. Alreary a tutorial ready for it, I am about to publish it, probably on Monday, so I will share with you with a free medium link when it's up. Along with the other tutorials as well of this series. Btw, Have followed you @tomasvotava , will check about contact info to share when ready 😃
